name: code analyzer
on:
  push:
    branches: ["main"]
  #  pull_request:
    # types: [opened, synchronize, reopened]
jobs:
  sonarQubeRrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest-java # Consider using a more specific runner
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "main"
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

